runtime: php73

env_variables:
    PROJECT_NAME: "locationconnection"
    
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

vpc_access_connector:
  name: projects/locationconnection/locations/europe-west3/connectors/vpcaccess                   